/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionItemsRouteImport } from './routes/action-items'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as MarketIntelligenceRouteImport } from './routes/market-intelligence'
import { Route as SalesAdvisorsRouteImport } from './routes/sales-advisors'
import { Route as TravellersRouteImport } from './routes/travellers'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as DestinationsIndexRouteImport } from './routes/destinations.index'
import { Route as DestinationsIdRouteImport } from './routes/destinations.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionItemsRoute = ActionItemsRouteImport.update({
  id: '/action-items',
  path: '/action-items',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIntelligenceRoute = MarketIntelligenceRouteImport.update({
  id: '/market-intelligence',
  path: '/market-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesAdvisorsRoute = SalesAdvisorsRouteImport.update({
  id: '/sales-advisors',
  path: '/sales-advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const TravellersRoute = TravellersRouteImport.update({
  id: '/travellers',
  path: '/travellers',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIndexRoute = DestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsIdRoute = DestinationsIdRouteImport.update({
  id: '/destinations/$id',
  path: '/destinations/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/calls': typeof CallsRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/sales-advisors': typeof SalesAdvisorsRoute
  '/travellers': typeof TravellersRoute
  '/whatsapp': typeof WhatsappRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/calls': typeof CallsRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/sales-advisors': typeof SalesAdvisorsRoute
  '/travellers': typeof TravellersRoute
  '/whatsapp': typeof WhatsappRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/destinations': typeof DestinationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/calls': typeof CallsRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/sales-advisors': typeof SalesAdvisorsRoute
  '/travellers': typeof TravellersRoute
  '/whatsapp': typeof WhatsappRoute
  '/destinations/$id': typeof DestinationsIdRoute
  '/destinations/': typeof DestinationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-items'
    | '/ai-insights'
    | '/calls'
    | '/market-intelligence'
    | '/sales-advisors'
    | '/travellers'
    | '/whatsapp'
    | '/destinations/$id'
    | '/destinations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-items'
    | '/ai-insights'
    | '/calls'
    | '/market-intelligence'
    | '/sales-advisors'
    | '/travellers'
    | '/whatsapp'
    | '/destinations/$id'
    | '/destinations'
  id:
    | '__root__'
    | '/'
    | '/action-items'
    | '/ai-insights'
    | '/calls'
    | '/market-intelligence'
    | '/sales-advisors'
    | '/travellers'
    | '/whatsapp'
    | '/destinations/$id'
    | '/destinations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionItemsRoute: typeof ActionItemsRoute
  AiInsightsRoute: typeof AiInsightsRoute
  CallsRoute: typeof CallsRoute
  MarketIntelligenceRoute: typeof MarketIntelligenceRoute
  SalesAdvisorsRoute: typeof SalesAdvisorsRoute
  TravellersRoute: typeof TravellersRoute
  WhatsappRoute: typeof WhatsappRoute
  DestinationsIdRoute: typeof DestinationsIdRoute
  DestinationsIndexRoute: typeof DestinationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-items': {
      id: '/action-items'
      path: '/action-items'
      fullPath: '/action-items'
      preLoaderRoute: typeof ActionItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-intelligence': {
      id: '/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof MarketIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-advisors': {
      id: '/sales-advisors'
      path: '/sales-advisors'
      fullPath: '/sales-advisors'
      preLoaderRoute: typeof SalesAdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travellers': {
      id: '/travellers'
      path: '/travellers'
      fullPath: '/travellers'
      preLoaderRoute: typeof TravellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/': {
      id: '/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof DestinationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations/$id': {
      id: '/destinations/$id'
      path: '/destinations/$id'
      fullPath: '/destinations/$id'
      preLoaderRoute: typeof DestinationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionItemsRoute: ActionItemsRoute,
  AiInsightsRoute: AiInsightsRoute,
  CallsRoute: CallsRoute,
  MarketIntelligenceRoute: MarketIntelligenceRoute,
  SalesAdvisorsRoute: SalesAdvisorsRoute,
  TravellersRoute: TravellersRoute,
  WhatsappRoute: WhatsappRoute,
  DestinationsIdRoute: DestinationsIdRoute,
  DestinationsIndexRoute: DestinationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
