/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoApplicantIntelligenceRouteImport } from './routes/demo.applicant-intelligence'
import { Route as DemoEmergingIssuesRouteImport } from './routes/demo.emerging-issues'
import { Route as DemoReportsRouteImport } from './routes/demo.reports'
import { Route as DemoResolutionRouteImport } from './routes/demo.resolution'
import { Route as DemoAgentsIndexRouteImport } from './routes/demo.agents.index'
import { Route as DemoContactDriversIndexRouteImport } from './routes/demo.contact-drivers.index'
import { Route as DemoContactDriversIdRouteImport } from './routes/demo.contact-drivers.$id'
import { Route as DemoConversationsIndexRouteImport } from './routes/demo.conversations.index'
import { Route as DemoConversationsIdRouteImport } from './routes/demo.conversations.$id'
import { Route as DemoLanguagesIdRouteImport } from './routes/demo.languages.$id'
import { Route as DemoMarketsIdRouteImport } from './routes/demo.markets.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoApplicantIntelligenceRoute =
  DemoApplicantIntelligenceRouteImport.update({
    id: '/applicant-intelligence',
    path: '/applicant-intelligence',
    getParentRoute: () => DemoRoute,
  } as any)
const DemoEmergingIssuesRoute = DemoEmergingIssuesRouteImport.update({
  id: '/emerging-issues',
  path: '/emerging-issues',
  getParentRoute: () => DemoRoute,
} as any)
const DemoReportsRoute = DemoReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DemoRoute,
} as any)
const DemoResolutionRoute = DemoResolutionRouteImport.update({
  id: '/resolution',
  path: '/resolution',
  getParentRoute: () => DemoRoute,
} as any)
const DemoAgentsIndexRoute = DemoAgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoContactDriversIndexRoute = DemoContactDriversIndexRouteImport.update({
  id: '/contact-drivers/',
  path: '/contact-drivers/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoContactDriversIdRoute = DemoContactDriversIdRouteImport.update({
  id: '/contact-drivers/$id',
  path: '/contact-drivers/$id',
  getParentRoute: () => DemoRoute,
} as any)
const DemoConversationsIndexRoute = DemoConversationsIndexRouteImport.update({
  id: '/conversations/',
  path: '/conversations/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoConversationsIdRoute = DemoConversationsIdRouteImport.update({
  id: '/conversations/$id',
  path: '/conversations/$id',
  getParentRoute: () => DemoRoute,
} as any)
const DemoLanguagesIdRoute = DemoLanguagesIdRouteImport.update({
  id: '/languages/$id',
  path: '/languages/$id',
  getParentRoute: () => DemoRoute,
} as any)
const DemoMarketsIdRoute = DemoMarketsIdRouteImport.update({
  id: '/markets/$id',
  path: '/markets/$id',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/demo/applicant-intelligence': typeof DemoApplicantIntelligenceRoute
  '/demo/emerging-issues': typeof DemoEmergingIssuesRoute
  '/demo/reports': typeof DemoReportsRoute
  '/demo/resolution': typeof DemoResolutionRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/contact-drivers/$id': typeof DemoContactDriversIdRoute
  '/demo/conversations/$id': typeof DemoConversationsIdRoute
  '/demo/languages/$id': typeof DemoLanguagesIdRoute
  '/demo/markets/$id': typeof DemoMarketsIdRoute
  '/demo/agents/': typeof DemoAgentsIndexRoute
  '/demo/contact-drivers/': typeof DemoContactDriversIndexRoute
  '/demo/conversations/': typeof DemoConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/demo/applicant-intelligence': typeof DemoApplicantIntelligenceRoute
  '/demo/emerging-issues': typeof DemoEmergingIssuesRoute
  '/demo/reports': typeof DemoReportsRoute
  '/demo/resolution': typeof DemoResolutionRoute
  '/demo': typeof DemoIndexRoute
  '/demo/contact-drivers/$id': typeof DemoContactDriversIdRoute
  '/demo/conversations/$id': typeof DemoConversationsIdRoute
  '/demo/languages/$id': typeof DemoLanguagesIdRoute
  '/demo/markets/$id': typeof DemoMarketsIdRoute
  '/demo/agents': typeof DemoAgentsIndexRoute
  '/demo/contact-drivers': typeof DemoContactDriversIndexRoute
  '/demo/conversations': typeof DemoConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/demo/applicant-intelligence': typeof DemoApplicantIntelligenceRoute
  '/demo/emerging-issues': typeof DemoEmergingIssuesRoute
  '/demo/reports': typeof DemoReportsRoute
  '/demo/resolution': typeof DemoResolutionRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/contact-drivers/$id': typeof DemoContactDriversIdRoute
  '/demo/conversations/$id': typeof DemoConversationsIdRoute
  '/demo/languages/$id': typeof DemoLanguagesIdRoute
  '/demo/markets/$id': typeof DemoMarketsIdRoute
  '/demo/agents/': typeof DemoAgentsIndexRoute
  '/demo/contact-drivers/': typeof DemoContactDriversIndexRoute
  '/demo/conversations/': typeof DemoConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/register'
    | '/demo/applicant-intelligence'
    | '/demo/emerging-issues'
    | '/demo/reports'
    | '/demo/resolution'
    | '/demo/'
    | '/demo/contact-drivers/$id'
    | '/demo/conversations/$id'
    | '/demo/languages/$id'
    | '/demo/markets/$id'
    | '/demo/agents/'
    | '/demo/contact-drivers/'
    | '/demo/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/demo/applicant-intelligence'
    | '/demo/emerging-issues'
    | '/demo/reports'
    | '/demo/resolution'
    | '/demo'
    | '/demo/contact-drivers/$id'
    | '/demo/conversations/$id'
    | '/demo/languages/$id'
    | '/demo/markets/$id'
    | '/demo/agents'
    | '/demo/contact-drivers'
    | '/demo/conversations'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/register'
    | '/demo/applicant-intelligence'
    | '/demo/emerging-issues'
    | '/demo/reports'
    | '/demo/resolution'
    | '/demo/'
    | '/demo/contact-drivers/$id'
    | '/demo/conversations/$id'
    | '/demo/languages/$id'
    | '/demo/markets/$id'
    | '/demo/agents/'
    | '/demo/contact-drivers/'
    | '/demo/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/applicant-intelligence': {
      id: '/demo/applicant-intelligence'
      path: '/applicant-intelligence'
      fullPath: '/demo/applicant-intelligence'
      preLoaderRoute: typeof DemoApplicantIntelligenceRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/emerging-issues': {
      id: '/demo/emerging-issues'
      path: '/emerging-issues'
      fullPath: '/demo/emerging-issues'
      preLoaderRoute: typeof DemoEmergingIssuesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/reports': {
      id: '/demo/reports'
      path: '/reports'
      fullPath: '/demo/reports'
      preLoaderRoute: typeof DemoReportsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/resolution': {
      id: '/demo/resolution'
      path: '/resolution'
      fullPath: '/demo/resolution'
      preLoaderRoute: typeof DemoResolutionRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/agents/': {
      id: '/demo/agents/'
      path: '/agents'
      fullPath: '/demo/agents/'
      preLoaderRoute: typeof DemoAgentsIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/contact-drivers/': {
      id: '/demo/contact-drivers/'
      path: '/contact-drivers'
      fullPath: '/demo/contact-drivers/'
      preLoaderRoute: typeof DemoContactDriversIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/contact-drivers/$id': {
      id: '/demo/contact-drivers/$id'
      path: '/contact-drivers/$id'
      fullPath: '/demo/contact-drivers/$id'
      preLoaderRoute: typeof DemoContactDriversIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/conversations/': {
      id: '/demo/conversations/'
      path: '/conversations'
      fullPath: '/demo/conversations/'
      preLoaderRoute: typeof DemoConversationsIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/conversations/$id': {
      id: '/demo/conversations/$id'
      path: '/conversations/$id'
      fullPath: '/demo/conversations/$id'
      preLoaderRoute: typeof DemoConversationsIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/languages/$id': {
      id: '/demo/languages/$id'
      path: '/languages/$id'
      fullPath: '/demo/languages/$id'
      preLoaderRoute: typeof DemoLanguagesIdRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/markets/$id': {
      id: '/demo/markets/$id'
      path: '/markets/$id'
      fullPath: '/demo/markets/$id'
      preLoaderRoute: typeof DemoMarketsIdRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoApplicantIntelligenceRoute: typeof DemoApplicantIntelligenceRoute
  DemoEmergingIssuesRoute: typeof DemoEmergingIssuesRoute
  DemoReportsRoute: typeof DemoReportsRoute
  DemoResolutionRoute: typeof DemoResolutionRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoContactDriversIdRoute: typeof DemoContactDriversIdRoute
  DemoConversationsIdRoute: typeof DemoConversationsIdRoute
  DemoLanguagesIdRoute: typeof DemoLanguagesIdRoute
  DemoMarketsIdRoute: typeof DemoMarketsIdRoute
  DemoAgentsIndexRoute: typeof DemoAgentsIndexRoute
  DemoContactDriversIndexRoute: typeof DemoContactDriversIndexRoute
  DemoConversationsIndexRoute: typeof DemoConversationsIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoApplicantIntelligenceRoute: DemoApplicantIntelligenceRoute,
  DemoEmergingIssuesRoute: DemoEmergingIssuesRoute,
  DemoReportsRoute: DemoReportsRoute,
  DemoResolutionRoute: DemoResolutionRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoContactDriversIdRoute: DemoContactDriversIdRoute,
  DemoConversationsIdRoute: DemoConversationsIdRoute,
  DemoLanguagesIdRoute: DemoLanguagesIdRoute,
  DemoMarketsIdRoute: DemoMarketsIdRoute,
  DemoAgentsIndexRoute: DemoAgentsIndexRoute,
  DemoContactDriversIndexRoute: DemoContactDriversIndexRoute,
  DemoConversationsIndexRoute: DemoConversationsIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
