/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DemoIndexRouteImport } from './routes/demo.index'
import { Route as DemoActionCentreRouteImport } from './routes/demo.action-centre'
import { Route as DemoDoctorsRouteImport } from './routes/demo.doctors'
import { Route as DemoEnquiriesRouteImport } from './routes/demo.enquiries'
import { Route as DemoEnquiryTeamRouteImport } from './routes/demo.enquiry-team'
import { Route as DemoPatientAccessRouteImport } from './routes/demo.patient-access'
import { Route as DemoPatientExperienceRouteImport } from './routes/demo.patient-experience'
import { Route as DemoPatientsRouteImport } from './routes/demo.patients'
import { Route as DemoSpecialtiesIndexRouteImport } from './routes/demo.specialties.index'
import { Route as DemoSpecialtiesIdRouteImport } from './routes/demo.specialties.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoIndexRoute = DemoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoActionCentreRoute = DemoActionCentreRouteImport.update({
  id: '/action-centre',
  path: '/action-centre',
  getParentRoute: () => DemoRoute,
} as any)
const DemoDoctorsRoute = DemoDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => DemoRoute,
} as any)
const DemoEnquiriesRoute = DemoEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => DemoRoute,
} as any)
const DemoEnquiryTeamRoute = DemoEnquiryTeamRouteImport.update({
  id: '/enquiry-team',
  path: '/enquiry-team',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPatientAccessRoute = DemoPatientAccessRouteImport.update({
  id: '/patient-access',
  path: '/patient-access',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPatientExperienceRoute = DemoPatientExperienceRouteImport.update({
  id: '/patient-experience',
  path: '/patient-experience',
  getParentRoute: () => DemoRoute,
} as any)
const DemoPatientsRoute = DemoPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSpecialtiesIndexRoute = DemoSpecialtiesIndexRouteImport.update({
  id: '/specialties/',
  path: '/specialties/',
  getParentRoute: () => DemoRoute,
} as any)
const DemoSpecialtiesIdRoute = DemoSpecialtiesIdRouteImport.update({
  id: '/specialties/$id',
  path: '/specialties/$id',
  getParentRoute: () => DemoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/demo/action-centre': typeof DemoActionCentreRoute
  '/demo/doctors': typeof DemoDoctorsRoute
  '/demo/enquiries': typeof DemoEnquiriesRoute
  '/demo/enquiry-team': typeof DemoEnquiryTeamRoute
  '/demo/patient-access': typeof DemoPatientAccessRoute
  '/demo/patient-experience': typeof DemoPatientExperienceRoute
  '/demo/patients': typeof DemoPatientsRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/specialties/$id': typeof DemoSpecialtiesIdRoute
  '/demo/specialties/': typeof DemoSpecialtiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/demo/action-centre': typeof DemoActionCentreRoute
  '/demo/doctors': typeof DemoDoctorsRoute
  '/demo/enquiries': typeof DemoEnquiriesRoute
  '/demo/enquiry-team': typeof DemoEnquiryTeamRoute
  '/demo/patient-access': typeof DemoPatientAccessRoute
  '/demo/patient-experience': typeof DemoPatientExperienceRoute
  '/demo/patients': typeof DemoPatientsRoute
  '/demo': typeof DemoIndexRoute
  '/demo/specialties/$id': typeof DemoSpecialtiesIdRoute
  '/demo/specialties': typeof DemoSpecialtiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/demo/action-centre': typeof DemoActionCentreRoute
  '/demo/doctors': typeof DemoDoctorsRoute
  '/demo/enquiries': typeof DemoEnquiriesRoute
  '/demo/enquiry-team': typeof DemoEnquiryTeamRoute
  '/demo/patient-access': typeof DemoPatientAccessRoute
  '/demo/patient-experience': typeof DemoPatientExperienceRoute
  '/demo/patients': typeof DemoPatientsRoute
  '/demo/': typeof DemoIndexRoute
  '/demo/specialties/$id': typeof DemoSpecialtiesIdRoute
  '/demo/specialties/': typeof DemoSpecialtiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/login'
    | '/register'
    | '/demo/action-centre'
    | '/demo/doctors'
    | '/demo/enquiries'
    | '/demo/enquiry-team'
    | '/demo/patient-access'
    | '/demo/patient-experience'
    | '/demo/patients'
    | '/demo/'
    | '/demo/specialties/$id'
    | '/demo/specialties/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/demo/action-centre'
    | '/demo/doctors'
    | '/demo/enquiries'
    | '/demo/enquiry-team'
    | '/demo/patient-access'
    | '/demo/patient-experience'
    | '/demo/patients'
    | '/demo'
    | '/demo/specialties/$id'
    | '/demo/specialties'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/login'
    | '/register'
    | '/demo/action-centre'
    | '/demo/doctors'
    | '/demo/enquiries'
    | '/demo/enquiry-team'
    | '/demo/patient-access'
    | '/demo/patient-experience'
    | '/demo/patients'
    | '/demo/'
    | '/demo/specialties/$id'
    | '/demo/specialties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/': {
      id: '/demo/'
      path: '/'
      fullPath: '/demo/'
      preLoaderRoute: typeof DemoIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/action-centre': {
      id: '/demo/action-centre'
      path: '/action-centre'
      fullPath: '/demo/action-centre'
      preLoaderRoute: typeof DemoActionCentreRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/doctors': {
      id: '/demo/doctors'
      path: '/doctors'
      fullPath: '/demo/doctors'
      preLoaderRoute: typeof DemoDoctorsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/enquiries': {
      id: '/demo/enquiries'
      path: '/enquiries'
      fullPath: '/demo/enquiries'
      preLoaderRoute: typeof DemoEnquiriesRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/enquiry-team': {
      id: '/demo/enquiry-team'
      path: '/enquiry-team'
      fullPath: '/demo/enquiry-team'
      preLoaderRoute: typeof DemoEnquiryTeamRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/patient-access': {
      id: '/demo/patient-access'
      path: '/patient-access'
      fullPath: '/demo/patient-access'
      preLoaderRoute: typeof DemoPatientAccessRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/patient-experience': {
      id: '/demo/patient-experience'
      path: '/patient-experience'
      fullPath: '/demo/patient-experience'
      preLoaderRoute: typeof DemoPatientExperienceRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/patients': {
      id: '/demo/patients'
      path: '/patients'
      fullPath: '/demo/patients'
      preLoaderRoute: typeof DemoPatientsRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/specialties/': {
      id: '/demo/specialties/'
      path: '/specialties'
      fullPath: '/demo/specialties/'
      preLoaderRoute: typeof DemoSpecialtiesIndexRouteImport
      parentRoute: typeof DemoRoute
    }
    '/demo/specialties/$id': {
      id: '/demo/specialties/$id'
      path: '/specialties/$id'
      fullPath: '/demo/specialties/$id'
      preLoaderRoute: typeof DemoSpecialtiesIdRouteImport
      parentRoute: typeof DemoRoute
    }
  }
}

interface DemoRouteChildren {
  DemoActionCentreRoute: typeof DemoActionCentreRoute
  DemoDoctorsRoute: typeof DemoDoctorsRoute
  DemoEnquiriesRoute: typeof DemoEnquiriesRoute
  DemoEnquiryTeamRoute: typeof DemoEnquiryTeamRoute
  DemoPatientAccessRoute: typeof DemoPatientAccessRoute
  DemoPatientExperienceRoute: typeof DemoPatientExperienceRoute
  DemoPatientsRoute: typeof DemoPatientsRoute
  DemoIndexRoute: typeof DemoIndexRoute
  DemoSpecialtiesIdRoute: typeof DemoSpecialtiesIdRoute
  DemoSpecialtiesIndexRoute: typeof DemoSpecialtiesIndexRoute
}

const DemoRouteChildren: DemoRouteChildren = {
  DemoActionCentreRoute: DemoActionCentreRoute,
  DemoDoctorsRoute: DemoDoctorsRoute,
  DemoEnquiriesRoute: DemoEnquiriesRoute,
  DemoEnquiryTeamRoute: DemoEnquiryTeamRoute,
  DemoPatientAccessRoute: DemoPatientAccessRoute,
  DemoPatientExperienceRoute: DemoPatientExperienceRoute,
  DemoPatientsRoute: DemoPatientsRoute,
  DemoIndexRoute: DemoIndexRoute,
  DemoSpecialtiesIdRoute: DemoSpecialtiesIdRoute,
  DemoSpecialtiesIndexRoute: DemoSpecialtiesIndexRoute,
}

const DemoRouteWithChildren = DemoRoute._addFileChildren(DemoRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
