/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionItemsRouteImport } from './routes/action-items'
import { Route as AgentIntelligenceRouteImport } from './routes/agent-intelligence'
import { Route as ClaimsRouteImport } from './routes/claims'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ExecutiveIntelligenceRouteImport } from './routes/executive-intelligence'
import { Route as ProductIntelligenceRouteImport } from './routes/product-intelligence'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as RiskReviewRouteImport } from './routes/risk-review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionItemsRoute = ActionItemsRouteImport.update({
  id: '/action-items',
  path: '/action-items',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIntelligenceRoute = AgentIntelligenceRouteImport.update({
  id: '/agent-intelligence',
  path: '/agent-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaimsRoute = ClaimsRouteImport.update({
  id: '/claims',
  path: '/claims',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveIntelligenceRoute = ExecutiveIntelligenceRouteImport.update({
  id: '/executive-intelligence',
  path: '/executive-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIntelligenceRoute = ProductIntelligenceRouteImport.update({
  id: '/product-intelligence',
  path: '/product-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskReviewRoute = RiskReviewRouteImport.update({
  id: '/risk-review',
  path: '/risk-review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/agent-intelligence': typeof AgentIntelligenceRoute
  '/claims': typeof ClaimsRoute
  '/complaints': typeof ComplaintsRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/executive-intelligence': typeof ExecutiveIntelligenceRoute
  '/product-intelligence': typeof ProductIntelligenceRoute
  '/quotes': typeof QuotesRoute
  '/renewals': typeof RenewalsRoute
  '/risk-review': typeof RiskReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/agent-intelligence': typeof AgentIntelligenceRoute
  '/claims': typeof ClaimsRoute
  '/complaints': typeof ComplaintsRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/executive-intelligence': typeof ExecutiveIntelligenceRoute
  '/product-intelligence': typeof ProductIntelligenceRoute
  '/quotes': typeof QuotesRoute
  '/renewals': typeof RenewalsRoute
  '/risk-review': typeof RiskReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/agent-intelligence': typeof AgentIntelligenceRoute
  '/claims': typeof ClaimsRoute
  '/complaints': typeof ComplaintsRoute
  '/conversations': typeof ConversationsRoute
  '/customers': typeof CustomersRoute
  '/executive-intelligence': typeof ExecutiveIntelligenceRoute
  '/product-intelligence': typeof ProductIntelligenceRoute
  '/quotes': typeof QuotesRoute
  '/renewals': typeof RenewalsRoute
  '/risk-review': typeof RiskReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-items'
    | '/agent-intelligence'
    | '/claims'
    | '/complaints'
    | '/conversations'
    | '/customers'
    | '/executive-intelligence'
    | '/product-intelligence'
    | '/quotes'
    | '/renewals'
    | '/risk-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-items'
    | '/agent-intelligence'
    | '/claims'
    | '/complaints'
    | '/conversations'
    | '/customers'
    | '/executive-intelligence'
    | '/product-intelligence'
    | '/quotes'
    | '/renewals'
    | '/risk-review'
  id:
    | '__root__'
    | '/'
    | '/action-items'
    | '/agent-intelligence'
    | '/claims'
    | '/complaints'
    | '/conversations'
    | '/customers'
    | '/executive-intelligence'
    | '/product-intelligence'
    | '/quotes'
    | '/renewals'
    | '/risk-review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionItemsRoute: typeof ActionItemsRoute
  AgentIntelligenceRoute: typeof AgentIntelligenceRoute
  ClaimsRoute: typeof ClaimsRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ConversationsRoute: typeof ConversationsRoute
  CustomersRoute: typeof CustomersRoute
  ExecutiveIntelligenceRoute: typeof ExecutiveIntelligenceRoute
  ProductIntelligenceRoute: typeof ProductIntelligenceRoute
  QuotesRoute: typeof QuotesRoute
  RenewalsRoute: typeof RenewalsRoute
  RiskReviewRoute: typeof RiskReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-items': {
      id: '/action-items'
      path: '/action-items'
      fullPath: '/action-items'
      preLoaderRoute: typeof ActionItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-intelligence': {
      id: '/agent-intelligence'
      path: '/agent-intelligence'
      fullPath: '/agent-intelligence'
      preLoaderRoute: typeof AgentIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claims': {
      id: '/claims'
      path: '/claims'
      fullPath: '/claims'
      preLoaderRoute: typeof ClaimsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-intelligence': {
      id: '/executive-intelligence'
      path: '/executive-intelligence'
      fullPath: '/executive-intelligence'
      preLoaderRoute: typeof ExecutiveIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product-intelligence': {
      id: '/product-intelligence'
      path: '/product-intelligence'
      fullPath: '/product-intelligence'
      preLoaderRoute: typeof ProductIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-review': {
      id: '/risk-review'
      path: '/risk-review'
      fullPath: '/risk-review'
      preLoaderRoute: typeof RiskReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionItemsRoute: ActionItemsRoute,
  AgentIntelligenceRoute: AgentIntelligenceRoute,
  ClaimsRoute: ClaimsRoute,
  ComplaintsRoute: ComplaintsRoute,
  ConversationsRoute: ConversationsRoute,
  CustomersRoute: CustomersRoute,
  ExecutiveIntelligenceRoute: ExecutiveIntelligenceRoute,
  ProductIntelligenceRoute: ProductIntelligenceRoute,
  QuotesRoute: QuotesRoute,
  RenewalsRoute: RenewalsRoute,
  RiskReviewRoute: RiskReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
