/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ActionItemsRouteImport } from './routes/action-items'
import { Route as AiInsightsRouteImport } from './routes/ai-insights'
import { Route as BuyersRouteImport } from './routes/buyers'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ExecutiveIntelligenceRouteImport } from './routes/executive-intelligence'
import { Route as MarketIntelligenceRouteImport } from './routes/market-intelligence'
import { Route as SalesAdvisorsRouteImport } from './routes/sales-advisors'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ActionItemsRoute = ActionItemsRouteImport.update({
  id: '/action-items',
  path: '/action-items',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInsightsRoute = AiInsightsRouteImport.update({
  id: '/ai-insights',
  path: '/ai-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyersRoute = BuyersRouteImport.update({
  id: '/buyers',
  path: '/buyers',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveIntelligenceRoute = ExecutiveIntelligenceRouteImport.update({
  id: '/executive-intelligence',
  path: '/executive-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIntelligenceRoute = MarketIntelligenceRouteImport.update({
  id: '/market-intelligence',
  path: '/market-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesAdvisorsRoute = SalesAdvisorsRouteImport.update({
  id: '/sales-advisors',
  path: '/sales-advisors',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/buyers': typeof BuyersRoute
  '/calls': typeof CallsRoute
  '/executive-intelligence': typeof ExecutiveIntelligenceRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/sales-advisors': typeof SalesAdvisorsRoute
  '/whatsapp': typeof WhatsappRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/buyers': typeof BuyersRoute
  '/calls': typeof CallsRoute
  '/executive-intelligence': typeof ExecutiveIntelligenceRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/sales-advisors': typeof SalesAdvisorsRoute
  '/whatsapp': typeof WhatsappRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/action-items': typeof ActionItemsRoute
  '/ai-insights': typeof AiInsightsRoute
  '/buyers': typeof BuyersRoute
  '/calls': typeof CallsRoute
  '/executive-intelligence': typeof ExecutiveIntelligenceRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/sales-advisors': typeof SalesAdvisorsRoute
  '/whatsapp': typeof WhatsappRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/action-items'
    | '/ai-insights'
    | '/buyers'
    | '/calls'
    | '/executive-intelligence'
    | '/market-intelligence'
    | '/sales-advisors'
    | '/whatsapp'
    | '/projects/$id'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/action-items'
    | '/ai-insights'
    | '/buyers'
    | '/calls'
    | '/executive-intelligence'
    | '/market-intelligence'
    | '/sales-advisors'
    | '/whatsapp'
    | '/projects/$id'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/action-items'
    | '/ai-insights'
    | '/buyers'
    | '/calls'
    | '/executive-intelligence'
    | '/market-intelligence'
    | '/sales-advisors'
    | '/whatsapp'
    | '/projects/$id'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActionItemsRoute: typeof ActionItemsRoute
  AiInsightsRoute: typeof AiInsightsRoute
  BuyersRoute: typeof BuyersRoute
  CallsRoute: typeof CallsRoute
  ExecutiveIntelligenceRoute: typeof ExecutiveIntelligenceRoute
  MarketIntelligenceRoute: typeof MarketIntelligenceRoute
  SalesAdvisorsRoute: typeof SalesAdvisorsRoute
  WhatsappRoute: typeof WhatsappRoute
  ProjectsIdRoute: typeof ProjectsIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/action-items': {
      id: '/action-items'
      path: '/action-items'
      fullPath: '/action-items'
      preLoaderRoute: typeof ActionItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-insights': {
      id: '/ai-insights'
      path: '/ai-insights'
      fullPath: '/ai-insights'
      preLoaderRoute: typeof AiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyers': {
      id: '/buyers'
      path: '/buyers'
      fullPath: '/buyers'
      preLoaderRoute: typeof BuyersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-intelligence': {
      id: '/executive-intelligence'
      path: '/executive-intelligence'
      fullPath: '/executive-intelligence'
      preLoaderRoute: typeof ExecutiveIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-intelligence': {
      id: '/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof MarketIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-advisors': {
      id: '/sales-advisors'
      path: '/sales-advisors'
      fullPath: '/sales-advisors'
      preLoaderRoute: typeof SalesAdvisorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/projects/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActionItemsRoute: ActionItemsRoute,
  AiInsightsRoute: AiInsightsRoute,
  BuyersRoute: BuyersRoute,
  CallsRoute: CallsRoute,
  ExecutiveIntelligenceRoute: ExecutiveIntelligenceRoute,
  MarketIntelligenceRoute: MarketIntelligenceRoute,
  SalesAdvisorsRoute: SalesAdvisorsRoute,
  WhatsappRoute: WhatsappRoute,
  ProjectsIdRoute: ProjectsIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
